;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env15
	.byte $00
	.byte $30 ;instrument $02
	.word @env2,@env0,@env14
	.byte $00
	.byte $70 ;instrument $03
	.word @env3,@env0,@env0
	.byte $00
	.byte $70 ;instrument $04
	.word @env4,@env0,@env0
	.byte $00
	.byte $70 ;instrument $05
	.word @env5,@env0,@env0
	.byte $00
	.byte $70 ;instrument $06
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env7,@env0,@env0
	.byte $00
	.byte $70 ;instrument $08
	.word @env11,@env0,@env16
	.byte $00
	.byte $30 ;instrument $09
	.word @env7,@env0,@env16
	.byte $00
	.byte $70 ;instrument $0a
	.word @env8,@env0,@env17
	.byte $00
	.byte $30 ;instrument $0b
	.word @env9,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0d
	.word @env10,@env0,@env0
	.byte $00
	.byte $70 ;instrument $11
	.word @env12,@env0,@env17
	.byte $00
	.byte $70 ;instrument $14
	.word @env13,@env0,@env0
	.byte $00

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;1
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;2
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;3
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;4
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;5
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;6
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;7
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;8
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;9
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;10
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;11
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;12
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;13
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;14
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;15
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;16
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;17
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;18
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;19
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;20
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;21
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;22
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;23
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;24
	.byte $00+.lobyte(FT_DPCM_PTR),$05,$0f	;25
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;26
	.byte $02+.lobyte(FT_DPCM_PTR),$0a,$0f	;27
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;28
	.byte $05+.lobyte(FT_DPCM_PTR),$13,$0f	;29
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;30
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;31
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;32
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;33
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;34
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;35
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;36
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;37
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;38
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;39
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;40
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;41
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;42
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;43
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;44
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;45
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;46
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;47
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;48
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;49
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;50
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;51
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;52
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;53
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;54
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;55
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;56
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;57
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;58
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;59
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;60
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;61
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;62
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;63

@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$03,$c0,$00,$02
@env2:
	.byte $c1,$c0,$c1,$02,$c0,$c1,$c0,$c1,$c0,$c1,$02,$c0,$c1,$03,$c0,$c1
	.byte $03,$c0,$c1,$07,$c0,$c2,$c1,$c2,$02,$c1,$c2,$02,$c1,$c2,$c2,$c1
	.byte $c2,$05,$c1,$c2,$05,$c3,$03,$c2,$c3,$04,$c2,$c3,$06,$c2,$c3,$09
	.byte $c2,$c3,$08,$c2,$04,$c1,$c2,$08,$c1,$c2,$05,$c1,$c2,$c2,$c1,$12
	.byte $c0,$c1,$04,$c0,$c1,$c1,$c0,$c1,$c1,$c0,$c1,$c1,$c0,$c1,$c0,$00
	.byte $4e
@env3:
	.byte $c3,$02,$c0,$c1,$c0,$02,$c2,$02,$c0,$c2,$c0,$02,$c2,$c2,$c0,$c0
	.byte $c2,$c0,$02,$c2,$c2,$c0,$c0,$c2,$c0,$00,$18
@env4:
	.byte $c1,$c2,$c3,$c2,$c1,$00,$04
@env5:
	.byte $c2,$02,$c0,$00,$02
@env6:
	.byte $c3,$c4,$c3,$c2,$00,$03
@env7:
	.byte $c2,$03,$c1,$0a,$c0,$00,$04
@env8:
	.byte $c2,$c2,$c3,$02,$c4,$24,$c3,$c4,$c3,$c4,$c3,$c4,$c3,$c4,$c3,$c4
	.byte $c3,$c4,$c3,$c4,$c3,$17,$c2,$c3,$c2,$c3,$c2,$c3,$c2,$c3,$c2,$c3
	.byte $c2,$c3,$c2,$c3,$c2,$c3,$c2,$c3,$c2,$16,$c1,$c2,$c1,$c2,$c1,$c2
	.byte $c1,$c2,$c1,$c2,$c1,$c2,$c1,$c2,$c1,$c2,$c1,$c2,$c1,$0a,$c0,$c1
	.byte $06,$c0,$c1,$c1,$c0,$c1,$c1,$c0,$c1,$c0,$c1,$c0,$c1,$c0,$c1,$c0
	.byte $02,$c1,$c0,$02,$c1,$c0,$03,$c1,$c0,$00,$58
@env9:
	.byte $c4,$c2,$c1,$04,$c0,$00,$04
@env10:
	.byte $cf,$00,$00
@env11:
	.byte $c2,$c3,$c2,$c2,$00,$03
@env12:
	.byte $c2,$2f,$c1,$4e,$c0,$00,$04
@env13:
	.byte $c1,$02,$c0,$00,$02
@env14:
	.byte $ca,$00,$00
@env15:
	.byte $c1,$c1,$c2,$c2,$c3,$c3,$c4,$c4,$c5,$c5,$c6,$c6,$c5,$c5,$c4,$c4
	.byte $c3,$c3,$c2,$c2,$c1,$c1,$c0,$c0,$00,$00
@env16:
	.byte $c2,$00,$00
@env17:
	.byte $c0,$11,$c1,$03,$c2,$03,$c1,$03,$c0,$02,$c0,$00,$02


@song0ch0:
	.byte $fb,$06
@ref0:
	.byte $82,$06,$9d
@ref1:
	.byte $9f
@ref2:
	.byte $06,$9d
@ref3:
	.byte $8e,$06,$0c,$14,$1e,$2c,$00,$83,$84,$24,$8d
@ref4:
	.byte $82,$06,$9d
@ref5:
	.byte $9f
@ref6:
	.byte $06,$9d
@ref7:
	.byte $92,$06,$14,$1e,$24,$2c,$00,$83,$82,$24,$8d
@song0ch0loop:
@ref8:
	.byte $8c,$07,$1f,$8e,$1e,$8c,$1f,$8e,$1e,$8c,$1a,$1f,$8e,$1a,$8c,$1e
	.byte $8e,$1e,$8c,$02,$81
@ref9:
	.byte $07,$1f,$8e,$1e,$8c,$1f,$8e,$1e,$8c,$1a,$1f,$8e,$1a,$8c,$24,$8e
	.byte $1e,$8c,$22,$8e,$24
@ref10:
	.byte $8c,$06,$8e,$22,$8c,$1f,$8e,$1e,$8c,$1f,$8e,$1e,$8c,$1a,$1f,$8e
	.byte $1a,$8c,$1e,$8e,$1e,$8c,$02,$81
@ref11:
	.byte $07,$1f,$8e,$1e,$8c,$1f,$8e,$1e,$8c,$25,$8e,$25,$8c,$25,$22,$81
@ref12:
	.byte $07,$1f,$8e,$1e,$8c,$1f,$8e,$1e,$8c,$1a,$1f,$8e,$1a,$8c,$1e,$8e
	.byte $1e,$8c,$02,$81
	.byte $ff,$0c
	.word @ref9
	.byte $ff,$0d
	.word @ref10
	.byte $ff,$0a
	.word @ref11
@ref16:
	.byte $1f,$8e,$1f,$8c,$1e,$2c,$36,$40,$44,$94,$36,$3c,$44,$4b,$44,$81
@ref17:
	.byte $87,$4a,$95
@ref18:
	.byte $87,$8c,$44,$3c,$36,$3c,$44,$8e,$36,$94,$36,$3c,$45,$48,$81
@ref19:
	.byte $97,$8c,$29,$24,$81
@ref20:
	.byte $1f,$8e,$1f,$8c,$1e,$2c,$36,$40,$44,$94,$36,$40,$44,$4b,$44,$81
@ref21:
	.byte $87,$4a,$95
	.byte $ff,$0c
	.word @ref18
	.byte $ff,$04
	.word @ref19
@ref24:
	.byte $94,$3a,$3c,$8b,$9a,$3c,$85,$94,$33,$2c,$81
@ref25:
	.byte $87,$9a,$33,$2c,$85,$94,$2c,$32,$3c,$2c,$32,$3c
@ref26:
	.byte $40,$95,$44,$85
@ref27:
	.byte $8f,$9a,$44,$85,$94,$3c,$3a,$36,$3a
@ref28:
	.byte $36,$8d,$9a,$36,$83,$94,$3a,$3d,$3a,$81
@ref29:
	.byte $85,$9a,$3a,$3d,$3a,$87,$94,$36,$3b,$44,$81
@ref30:
	.byte $8f,$9a,$44,$85,$94,$44,$8e,$2c,$94,$4a,$8e,$32
@ref31:
	.byte $83,$01,$94,$44,$8e,$2c,$83,$94,$40,$8e,$28,$94,$3c,$8e,$24,$87
	.byte $ff,$08
	.word @ref24
	.byte $ff,$0a
	.word @ref25
@ref34:
	.byte $40,$95,$44,$85
	.byte $ff,$07
	.word @ref27
@ref36:
	.byte $3c,$93,$30,$33,$40,$81
@ref37:
	.byte $85,$9a,$30,$33,$40,$87,$94,$28,$2d,$36,$81
@ref38:
	.byte $9f
@ref39:
	.byte $9f
@ref40:
	.byte $82,$06,$9d
@ref41:
	.byte $9f
@ref42:
	.byte $06,$9d
	.byte $ff,$09
	.word @ref3
@ref44:
	.byte $82,$06,$9d
@ref45:
	.byte $9f
@ref46:
	.byte $06,$9d
	.byte $ff,$09
	.word @ref7
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref48:
	.byte $97,$84,$06,$85
@ref49:
	.byte $9f
@ref50:
	.byte $97,$8c,$06,$0c,$14,$1e
@ref51:
	.byte $2c,$00,$8b,$84,$24,$8d
@ref52:
	.byte $00,$95,$06,$85
@ref53:
	.byte $9f
@ref54:
	.byte $97,$90,$06,$14,$1e,$24
	.byte $ff,$05
	.word @ref51
@song0ch1loop:
@ref56:
	.byte $90,$07,$1f,$92,$1e,$90,$1f,$92,$1e,$90,$1a,$1f,$92,$1a,$90,$1e
	.byte $92,$1e,$90,$02,$81
@ref57:
	.byte $07,$1f,$92,$1e,$90,$1f,$92,$1e,$90,$1a,$1f,$92,$1a,$90,$24,$92
	.byte $1e,$90,$22,$92,$24
@ref58:
	.byte $90,$06,$92,$22,$90,$1f,$92,$1e,$90,$1f,$92,$1e,$90,$1a,$1f,$92
	.byte $1a,$90,$1e,$92,$1e,$90,$02,$81
@ref59:
	.byte $07,$1f,$92,$1e,$90,$1f,$92,$1e,$90,$25,$92,$25,$90,$25,$22,$81
@ref60:
	.byte $07,$1f,$92,$1e,$90,$1f,$92,$1e,$90,$1a,$1f,$92,$1a,$90,$1e,$92
	.byte $1e,$90,$02,$81
	.byte $ff,$0c
	.word @ref57
	.byte $ff,$0d
	.word @ref58
	.byte $ff,$0a
	.word @ref59
@ref64:
	.byte $1f,$92,$1f,$90,$36,$44,$4e,$58,$5c,$92,$4e,$58,$5c,$8e,$36,$40
	.byte $9a,$4a,$81
@ref65:
	.byte $44,$89,$4a,$91
@ref66:
	.byte $87,$90,$5c,$54,$4e,$54,$5c,$92,$4e,$54,$5c,$8e,$4e,$54,$9a,$44
	.byte $81
@ref67:
	.byte $48,$95,$90,$29,$24,$81
	.byte $ff,$0e
	.word @ref64
@ref69:
	.byte $44,$89,$4a,$91
	.byte $ff,$0d
	.word @ref66
	.byte $ff,$05
	.word @ref67
@ref72:
	.byte $8c,$16,$1e,$24,$2c,$32,$2c,$24,$1e,$16,$1e,$24,$2c,$32,$2c,$24
	.byte $1e
@ref73:
	.byte $1a,$22,$28,$32,$3a,$32,$28,$22,$1a,$22,$90,$44,$4a,$54,$44,$4a
	.byte $54
@ref74:
	.byte $92,$44,$4a,$54,$8c,$36,$3c,$36,$2c,$24,$1e,$24,$2c,$36,$3c,$36
	.byte $2c,$24
@ref75:
	.byte $1e,$24,$2c,$36,$3c,$36,$2c,$24,$1e,$24,$2c,$36,$3c,$36,$2c,$24
@ref76:
	.byte $16,$1e,$24,$2c,$32,$2c,$24,$1e,$16,$1e,$24,$2c,$32,$2c,$24,$1e
@ref77:
	.byte $1a,$22,$28,$32,$3a,$32,$28,$22,$1a,$22,$28,$32,$3a,$32,$28,$22
@ref78:
	.byte $1e,$24,$2c,$36,$3c,$36,$2c,$24,$1e,$24,$2c,$36,$90,$44,$92,$44
	.byte $90,$4a,$92,$4a
@ref79:
	.byte $8c,$1e,$24,$2c,$36,$90,$44,$92,$44,$8c,$2c,$24,$90,$40,$92,$40
	.byte $90,$3c,$92,$3c,$8c,$3c,$36,$2c,$24
	.byte $ff,$10
	.word @ref76
	.byte $ff,$10
	.word @ref73
	.byte $ff,$10
	.word @ref74
	.byte $ff,$10
	.word @ref75
	.byte $ff,$10
	.word @ref76
	.byte $ff,$10
	.word @ref77
	.byte $ff,$10
	.word @ref75
@ref87:
	.byte $1e,$24,$2c,$36,$3c,$36,$2c,$24,$37,$8e,$37,$00,$85
@ref88:
	.byte $97,$84,$06,$85
@ref89:
	.byte $9f
	.byte $ff,$05
	.word @ref50
	.byte $ff,$05
	.word @ref51
@ref92:
	.byte $00,$95,$06,$85
@ref93:
	.byte $9f
	.byte $ff,$05
	.word @ref54
	.byte $ff,$05
	.word @ref51
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref96:
	.byte $98,$06,$85,$00,$91,$02,$81
@ref97:
	.byte $06,$85,$00,$95
@ref98:
	.byte $06,$85,$00,$91,$02,$81
@ref99:
	.byte $06,$85,$00,$95
	.byte $ff,$06
	.word @ref98
@ref101:
	.byte $06,$85,$00,$95
	.byte $ff,$06
	.word @ref98
@ref103:
	.byte $06,$85,$00,$95
@song0ch2loop:
@ref104:
	.byte $98,$1f,$80,$36,$83,$36,$83,$32,$36,$83,$37,$98,$1a,$81
@ref105:
	.byte $1f,$80,$36,$83,$36,$83,$32,$36,$83,$3d,$3a,$81
	.byte $ff,$0b
	.word @ref104
@ref107:
	.byte $1f,$80,$36,$83,$36,$83,$98,$25,$01,$25,$22,$81
@ref108:
	.byte $1f,$80,$36,$83,$36,$83,$32,$36,$83,$37,$98,$1a,$81
	.byte $ff,$0b
	.word @ref105
	.byte $ff,$0b
	.word @ref104
@ref111:
	.byte $1e,$8d,$18,$10,$0a,$02,$00,$85
	.byte $ff,$0b
	.word @ref108
	.byte $ff,$0b
	.word @ref105
@ref114:
	.byte $98,$25,$80,$3c,$83,$3c,$83,$3a,$3c,$83,$3d,$98,$24,$81
@ref115:
	.byte $29,$80,$40,$83,$40,$83,$40,$85,$98,$29,$24,$81
	.byte $ff,$0b
	.word @ref108
	.byte $ff,$0b
	.word @ref105
	.byte $ff,$0b
	.word @ref114
	.byte $ff,$0a
	.word @ref115
@ref120:
	.byte $17,$80,$2e,$83,$2e,$83,$2a,$2e,$83,$2f,$98,$12,$81
@ref121:
	.byte $1b,$80,$32,$83,$32,$83,$2e,$32,$83,$98,$17,$1a,$81
	.byte $ff,$0b
	.word @ref108
@ref123:
	.byte $25,$80,$3c,$83,$3c,$83,$3a,$3c,$83,$3d,$3a,$81
@ref124:
	.byte $98,$17,$80,$2e,$83,$2e,$83,$2a,$2e,$83,$2f,$98,$12,$81
	.byte $ff,$0b
	.word @ref121
	.byte $ff,$0b
	.word @ref108
@ref127:
	.byte $1f,$80,$36,$83,$36,$83,$32,$36,$83,$36,$85
	.byte $ff,$0b
	.word @ref124
	.byte $ff,$0b
	.word @ref121
	.byte $ff,$0b
	.word @ref108
	.byte $ff,$0b
	.word @ref123
	.byte $ff,$0b
	.word @ref124
	.byte $ff,$0b
	.word @ref121
	.byte $ff,$0b
	.word @ref108
@ref135:
	.byte $1e,$85,$14,$0c,$06,$00,$8f
	.byte $ff,$06
	.word @ref98
@ref137:
	.byte $06,$85,$00,$95
	.byte $ff,$06
	.word @ref98
@ref139:
	.byte $06,$85,$00,$95
	.byte $ff,$06
	.word @ref98
@ref141:
	.byte $06,$85,$00,$95
	.byte $ff,$06
	.word @ref98
@ref143:
	.byte $06,$85,$00,$95
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref144:
	.byte $01,$8a,$1b,$9c,$1a,$8a,$1b,$9c,$1a,$8a,$1a,$1b,$9c,$1a,$8a,$1a
	.byte $85
@ref145:
	.byte $9c,$1b,$8a,$1b,$9c,$1a,$8a,$1b,$9c,$1a,$8a,$1a,$1b,$9c,$1a,$88
	.byte $17,$9c,$12,$81
@ref146:
	.byte $83,$8a,$1b,$9c,$1a,$8a,$1b,$9c,$1a,$8a,$1a,$1b,$9c,$1a,$8a,$1b
	.byte $9c,$1a,$81
@ref147:
	.byte $83,$8a,$1b,$9c,$1a,$8a,$1b,$9c,$1a,$88,$18,$89,$9c,$12,$81
	.byte $ff,$0a
	.word @ref144
	.byte $ff,$0b
	.word @ref145
	.byte $ff,$0b
	.word @ref146
@ref151:
	.byte $83,$8a,$1b,$9c,$1a,$8a,$1b,$9c,$1a,$88,$1a,$85,$00,$85
@song0ch3loop:
@ref152:
	.byte $96,$1e,$1e,$8a,$1a,$96,$1e,$9c,$1a,$8a,$1a,$96,$1e,$9c,$1a,$8a
	.byte $1a,$1a,$96,$1e,$9c,$1a,$8a,$1a,$96,$1e,$1e,$1e
@ref153:
	.byte $9c,$1a,$96,$1e,$8a,$1a,$96,$1e,$9c,$1a,$8a,$1a,$96,$1e,$9c,$1a
	.byte $8a,$1a,$1a,$96,$1e,$9c,$1a,$88,$19,$96,$1e,$1e
@ref154:
	.byte $9c,$16,$96,$1e,$8a,$1a,$96,$1e,$9c,$1a,$8a,$1a,$96,$1e,$9c,$1a
	.byte $8a,$1a,$1a,$96,$1e,$9c,$1a,$8a,$1a,$96,$1e,$9c,$1a,$96,$1e
@ref155:
	.byte $1e,$1e,$8a,$1a,$96,$1e,$9c,$1a,$8a,$1a,$96,$1e,$9c,$1a,$88,$1a
	.byte $85,$96,$1e,$1e,$9c,$1a,$96,$1e
@ref156:
	.byte $1e,$1e,$8a,$1a,$96,$1e,$9c,$1a,$8a,$1a,$96,$1e,$9c,$1a,$8a,$1a
	.byte $1a,$96,$1e,$9c,$1a,$8a,$1a,$96,$1e,$1e,$1e
	.byte $ff,$0f
	.word @ref153
	.byte $ff,$10
	.word @ref154
@ref159:
	.byte $1f,$8a,$1b,$9c,$1a,$8a,$1b,$9c,$1a,$88,$1a,$85,$18,$16,$12,$0e
@ref160:
	.byte $96,$1a,$1e,$1c,$1e,$1a,$1e,$1c,$1e,$1a,$1e,$1c,$1e,$1a,$1e,$8a
	.byte $18,$18
@ref161:
	.byte $9c,$18,$18,$96,$1c,$1e,$1a,$1e,$1c,$1e,$1a,$1e,$1c,$1e,$8a,$18
	.byte $96,$1e,$8a,$16,$96,$1e
@ref162:
	.byte $9c,$16,$96,$1e,$1c,$1e,$1a,$1e,$1c,$1e,$1a,$1e,$1c,$1e,$1a,$1e
	.byte $8a,$18,$18
@ref163:
	.byte $9c,$18,$18,$96,$1c,$1e,$1a,$1e,$1c,$1e,$1a,$1e,$1c,$1e,$1e,$1e
	.byte $1e,$1e
@ref164:
	.byte $1a,$1e,$1c,$1e,$1a,$1e,$1c,$1e,$1a,$1e,$1c,$1e,$1a,$1e,$8a,$18
	.byte $18
	.byte $ff,$10
	.word @ref161
	.byte $ff,$10
	.word @ref162
	.byte $ff,$10
	.word @ref163
	.byte $ff,$10
	.word @ref162
	.byte $ff,$10
	.word @ref161
	.byte $ff,$10
	.word @ref162
	.byte $ff,$10
	.word @ref161
	.byte $ff,$10
	.word @ref162
	.byte $ff,$10
	.word @ref161
	.byte $ff,$10
	.word @ref162
	.byte $ff,$10
	.word @ref161
	.byte $ff,$10
	.word @ref162
	.byte $ff,$10
	.word @ref161
	.byte $ff,$10
	.word @ref162
	.byte $ff,$10
	.word @ref161
	.byte $ff,$10
	.word @ref162
	.byte $ff,$10
	.word @ref161
	.byte $ff,$10
	.word @ref162
@ref183:
	.byte $86,$1a,$9d
	.byte $ff,$0a
	.word @ref144
	.byte $ff,$0b
	.word @ref145
	.byte $ff,$0b
	.word @ref146
	.byte $ff,$09
	.word @ref147
	.byte $ff,$0a
	.word @ref144
	.byte $ff,$0b
	.word @ref145
	.byte $ff,$0b
	.word @ref146
	.byte $ff,$09
	.word @ref151
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref192:
	.byte $32,$99,$32,$81
@ref193:
	.byte $32,$9d
@ref194:
	.byte $32,$99,$32,$81
@ref195:
	.byte $32,$95,$32,$32,$32,$32
@ref196:
	.byte $32,$99,$32,$81
@ref197:
	.byte $32,$9d
@ref198:
	.byte $32,$99,$32,$81
@ref199:
	.byte $32,$8d,$32,$85,$3a,$3a,$3a,$3a
@song0ch4loop:
@ref200:
	.byte $32,$85,$3b,$36,$32,$83,$33,$3a,$32,$83
@ref201:
	.byte $32,$85,$3b,$36,$32,$83,$33,$3a,$85
	.byte $ff,$0a
	.word @ref200
@ref203:
	.byte $36,$36,$36,$36,$3b,$32,$32,$83,$36,$36,$3a,$85
@ref204:
	.byte $32,$85,$3b,$36,$32,$83,$33,$3a,$33,$32
@ref205:
	.byte $32,$85,$3b,$36,$32,$83,$33,$3b,$36,$36
@ref206:
	.byte $32,$85,$3b,$36,$32,$83,$36,$36,$3b,$32,$81
@ref207:
	.byte $3b,$33,$33,$33,$3a,$3b,$3a,$3a,$3a,$3a,$3a
@ref208:
	.byte $32,$85,$3a,$83,$32,$32,$85,$3b,$32,$81
@ref209:
	.byte $32,$85,$3a,$83,$32,$32,$85,$3a,$85
	.byte $ff,$0a
	.word @ref208
	.byte $ff,$09
	.word @ref209
	.byte $ff,$0a
	.word @ref208
	.byte $ff,$09
	.word @ref209
	.byte $ff,$0a
	.word @ref208
@ref215:
	.byte $32,$85,$3a,$83,$32,$32,$85,$3a,$3a,$3a,$3a
@ref216:
	.byte $33,$33,$3b,$36,$32,$83,$37,$3a,$33,$32
@ref217:
	.byte $33,$33,$3b,$36,$32,$83,$33,$3a,$85
@ref218:
	.byte $33,$33,$3b,$36,$32,$83,$33,$3a,$33,$32
	.byte $ff,$09
	.word @ref217
	.byte $ff,$0a
	.word @ref216
	.byte $ff,$09
	.word @ref217
	.byte $ff,$0a
	.word @ref218
@ref223:
	.byte $33,$33,$3b,$36,$33,$36,$37,$3b,$3a,$3a
	.byte $ff,$0a
	.word @ref216
	.byte $ff,$09
	.word @ref217
	.byte $ff,$0a
	.word @ref218
	.byte $ff,$09
	.word @ref217
	.byte $ff,$0a
	.word @ref218
	.byte $ff,$09
	.word @ref217
@ref230:
	.byte $33,$33,$3b,$36,$36,$83,$37,$3b,$32,$81
@ref231:
	.byte $33,$36,$36,$83,$37,$36,$36,$83,$3a,$85
@ref232:
	.byte $32,$99,$32,$81
@ref233:
	.byte $32,$9d
@ref234:
	.byte $32,$99,$32,$81
	.byte $ff,$06
	.word @ref195
@ref236:
	.byte $32,$85,$36,$8d,$37,$32,$81
@ref237:
	.byte $32,$85,$36,$8d,$36,$85
	.byte $ff,$07
	.word @ref236
@ref239:
	.byte $32,$85,$36,$85,$32,$85,$3a,$3a,$3a,$3a
	.byte $fd
	.word @song0ch4loop
